
title: Johan Vonk's Website
email: johan.d.s.vonk@gmail.com
description: My personal static website created using Github Pages, Markdown, and Jekyll
baseurl: ""
url: "https://jvonk.github.io"

github_username:  jvonk
github_url:  "https://github.com/jvonk/jvonk.github.io"
linkedin_url:  "https://www.linkedin.com/in/johan-vonk-337778171"

khan_url: "https://www.khanacademy.org/profile/vonkj"
khan_username: vonkj
github.is_project_page: true
repository: jvonk/jvonk.github.io
skip-to-content: false


markdown: kramdown
theme: jekyll-theme-cayman
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

algolia:
  application_id: 6Q0Q3C57UM
  index_name:     jekyll
  nodes_to_index: 'div.realcontent'
  vars: ["title", "excerpt", "date", "url", "categories", "tags", "short", "chapter", "section", "description", "content"]

kramdown:
  syntax_highlighter_opts:
    disable : true
  parse_block_html: true

tipue_search:
  include:
    pages: true